In [299]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (4.9.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (0.10.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: async-generator>=1.9 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sortedcontainers in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sniffio in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: outcome in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\admin\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\admin\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\admin\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [300]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [301]:
driver=webdriver.Chrome(r"C:\Users\Admin\Desktop\chromedriver.exe")

In [302]:
driver=webdriver.Chrome(r"chromedriver.exe")

In [303]:
driver.get("https://www.naukri.com/")

In [304]:
designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Analyst')

In [305]:
location=driver.find_element(By.XPATH,"/html/body/div[1]/div[7]/div/div/div[5]/div/div/div/div[1]/div/input")
location.send_keys('Bangalore')

In [306]:
Search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
Search.click()
time.sleep(3)

In [307]:
job_title=[]
job_location=[]
company_name=[]
experiance_required=[]

In [308]:
title_tags=driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)
location_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)
company_tags=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
experiance_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experiance_tags[0:10]:
    experiance=i.text
    experiance_required.append(experiance)

In [309]:
import pandas as pd
df=pd.DataFrame({'Title':job_title[0:10],'Location':job_location[0:10],'Company_name':company_name[0:10],'Experiance':experiance_required[0:10]})
df

,Title,Location,Company_name,Experiance
0,Data Analyst,Bangalore/Bengaluru,Target,2-4 Yrs
1,Tech Data Analyst,"Hybrid - Bangalore/ Bengaluru, Karnataka, Gurg...",Wipro,3-6 Yrs
2,Data Analyst,"Bangalore/ Bengaluru, Karnataka",Artech,5-8 Yrs
3,Data Analyst,Bangalore/Bengaluru,Brunel,4-6 Yrs
4,Celonis & Salesforce Data Analyst,"Bangalore/Bengaluru, Chennai",Hitachi Energy,3-6 Yrs
5,Celonis & Salesforce Data Analyst,Bangalore/Bengaluru,Hitachi Ltd.,2-7 Yrs
6,Data Analyst,Hybrid - Bangalore/Bengaluru,HARMAN,3-5 Yrs
7,Data Analyst,"Hybrid - Bangalore/Bengaluru, Delhi / NCR",Aon,6-9 Yrs
8,Data Analyst,"Hybrid - Bangalore/Bengaluru, Delhi / NCR",Aon,6-9 Yrs
9,Data Analyst,"Bangalore/Bengaluru, Kolkata, Hyderabad/Secund...",Tata Consultancy Services (TCS),5-10 Yrs

In [334]:
# Q2

driver.get("https://www.naukri.com/")

In [335]:
designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Scientist')

In [340]:

location=driver.find_element(By.XPATH,"/html/body/div[1]/div[7]/div/div/div[5]/div/div/div/div[1]/div/input")
location.send_keys('Bangalore')

In [341]:

search1=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search1.click()

In [342]:
job_title1=[]
job_location1=[]
company_name1=[]

In [343]:
title1_tags=driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title1_tags[0:10]:
    title1=i.text
    job_title1.append(title1)
location1_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location1_tags[0:10]:
    location1=i.text
    job_location1.append(location1)
company1_tags=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company1_tags[0:10]:
    company1=i.text
    company_name1.append(company1)

In [344]:
import pandas as pd
df2=pd.DataFrame({'Job Title':job_title1[0:10],'Location':job_location1[0:10],'Company_name':company_name1[0:10]})
df2

,Job Title,Location,Company_name
0,Permanent Opportunity - Data Scientist(Snaplog...,"Hybrid - Bangalore/Bengaluru, Kolkata, Hyderab...",Deloitte
1,Analystics & Modeling Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture
2,Machine Learning (AI) Architect,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Persistent
3,Staff Data Scientist,Bangalore/Bengaluru,Walmart
4,Data Scientist,"Bangalore/ Bengaluru, Karnataka",Tata Consultancy Services (TCS)
5,Hiring For Data Scientist,"Hybrid - Bangalore/ Bengaluru, Karnataka, Hyde...",Tata Consultancy Services (TCS)
6,Data Scientist,"Hybrid - Bangalore/Bengaluru, Pune, Delhi / NC...",Infogain
7,Director/Senior Director - Data Science,"Bangalore/Bengaluru, Noida, Hyderabad/Secunder...",Axtria India
8,Manager/Senior Manager - Data Science,"Bangalore/Bengaluru, Noida, Hyderabad/Secunder...",Axtria India
9,Data Scientist,Bangalore/Bengaluru,Ericsson

In [345]:
# Q3
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.naukri.com/")

In [346]:
designation=driver.find_element(By.CLASS_NAME,"suggestor-input ")
designation.send_keys('Data Scientist')

In [347]:
search12=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search12.click()

In [348]:
job_title2=[]
job_location2=[]
company_name2=[]
experiance_required2=[]

In [349]:
checkbox = driver.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/div/section[1]/div[2]/div[5]/div[2]/div[2]/label/p/span[1]")
checkbox.click()
time.sleep(3)

In [350]:
checkbox1 = driver.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/div/section[1]/div[2]/div[6]/div[2]/div[2]/label/p/span[1]")
checkbox1.click()
time.sleep(3)

In [351]:
title2_tags=driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title2_tags[0:10]:
    title2=i.text
    job_title2.append(title2)
location2_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location2_tags[0:10]:
    location2=i.text
    job_location2.append(location2)
company2_tags=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company2_tags[0:10]:
    company2=i.text
    company_name2.append(company2)
experiance2_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experiance2_tags[0:10]:
    experiance2=i.text
    experiance_required2.append(experiance2)

In [352]:
import pandas as pd
df3=pd.DataFrame({'Title':job_title2[0:10],'Location':job_location2[0:10],'Company_name':company_name2[0:10],'Experiance':experiance_required2[0:10]})
df3

,Title,Location,Company_name,Experiance
0,Junior Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Analytos,0-2 Yrs
1,Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru",Blackbuck,3-7 Yrs
2,Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Analytos,2-4 Yrs
3,Python and ML Trainer,"Hyderabad/Secunderabad, New Delhi, Pune, Gurga...",Thescholar,3-8 Yrs
4,Data Scientist,Delhi / NCR,Tata Consultancy Services (TCS),7-12 Yrs
5,Intern,Gurgaon/Gurugram,Tower Research Capital,0-1 Yrs
6,Lead Assistant Manager,Gurgaon/Gurugram,EXL,2-6 Yrs
7,Data Scientist,Noida,Innovaccer,2-4 Yrs
8,Junior Data Scientist,"Gurgaon/Gurugram, United States (USA), Bulgaria",Adidas,1-6 Yrs
9,MLOps - Data Scientist,Noida,Paytm,3-8 Yrs

In [353]:
# Q4
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.flipkart.com/")

In [354]:
close=driver.find_element(By.XPATH,"/html/body/div[2]/div/div/button")
close.click()

In [355]:
Product4=driver.find_element(By.CLASS_NAME,"_3704LK")
Product4.send_keys('Sun Glasses')

In [356]:
search4=driver.find_element(By.CLASS_NAME,"L0Z3Pu")
search4.click()

In [357]:
Brand=[]
Product_Description=[]
Price=[]

In [358]:
start=0
end=4
for page in range(start,end):
    Brands=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in Brands:
        Brand.append(i.text)
    Description=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in Description:
        Product_Description.append(i.text)
    Prices=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in Prices:
        Price.append(i.text)
    Next=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[2]")
    Next.click() 
    time.sleep(5)

In [359]:
print(len(Brand),len(Product_Description),len(Price))

160 156 160

In [360]:
import pandas as pd
df=pd.DataFrame({'Brand': Brand[0:100],'Product Description':Product_Description[0:100],'Price': Price[0:100]})
df

        Brand                                Product Description Price
0   ROYAL SON  UV Protection Rectangular, Retro Square Sungla...  ₹471
1   ROYAL SON              Polarized Rectangular Sunglasses (60)  ₹699
2        BKGE  Polarized, UV Protection Retro Square Sunglass...  ₹149
3    Fastrack   UV Protection Rectangular Sunglasses (Free Size)  ₹499
4   Elligator   UV Protection, Mirrored Wayfarer Sunglasses (54)  ₹109
..        ...                                                ...   ...
95     AISLIN             UV Protection Wayfarer Sunglasses (56)  ₹745
96  Elligator  UV Protection, Gradient Over-sized, Wayfarer S...  ₹149
97  Elligator        UV Protection Shield Sunglasses (Free Size)  ₹213
98     PIRASO             UV Protection Wayfarer Sunglasses (56)  ₹192
99      NuVew   UV Protection Rectangular Sunglasses (Free Size)  ₹403

[100 rows x 3 columns]

In [361]:
# Q5
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market")

In [362]:
Rating=[]
Review_summary=[]
Full_review=[]

In [363]:
start=0
end=12
for page in range(start,end):
    Ratings=driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    for i in Ratings:
        Rating.append(i.text)
    Review=driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    for i in Review:
        Review_summary.append(i.text)
    Fullreview=driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]')
    for i in Fullreview:
        Full_review.append(i.text)
    Next=driver.find_element(By.XPATH,"/html/body/div/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[2]")
    Next.click() 
    time.sleep(3)

In [364]:
print(len(Rating),len(Review_summary),len(Full_review))

120 120 120

In [365]:
import pandas as pd
df5=pd.DataFrame({'Rating': Rating[0:100],'Review summary':Review_summary[0:100],'Full_review': Full_review[0:100]})
df5

,Rating,Review summary,Full_review
0,5,Simply awesome,Really satisfied with the Product I received.....
1,5,Perfect product!,Amazing phone with great cameras and better ba...
2,5,Best in the market!,Great iPhone very snappy experience as apple k...
3,4,Value-for-money,I'm Really happy with the product\nDelivery wa...
4,5,Highly recommended,It's my first time to use iOS phone and I am l...
...,...,...,...
95,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
96,5,Highly recommended,iphone 11 is a very good phone to buy only if ...
97,5,Highly recommended,"Amazing camera quality as expected, battery al..."
98,4,Value-for-money,Just got this iphone 11\nAnd it is most powerf...
99,5,Perfect product!,It is just awesome mobile for this price from ...

In [366]:
# Q6
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.flipkart.com/")

In [367]:
close=driver.find_element(By.XPATH,"/html/body/div[2]/div/div/button")
close.click()

In [368]:
Product6=driver.find_element(By.CLASS_NAME,"_3704LK")
Product6.send_keys('Sneakers')

In [369]:
search6=driver.find_element(By.CLASS_NAME,"L0Z3Pu")
search6.click()

In [370]:
Brand6=[]
Product_Description6=[]
Price6=[]

In [371]:
start=0
end=3
for page in range(start,end):
    Brands6=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in Brands6:
        Brand6.append(i.text)
    Product_Descriptions6=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in Product_Descriptions6:
        Product_Description6.append(i.text)
    Prices6=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in Prices6:
        Price6.append(i.text)
    
    Next=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[2]")
    Next.click() 
    time.sleep(3)

In [ ]:
print(len(Brand6),len(Product_Description6),len(Price6))

In [372]:
import pandas as pd
df6=pd.DataFrame({'Brand6': Brand6[0:100],'Product Description6':Product_Description6[0:100],'Price6': Price6[0:100]})
df6

,Brand6,Product Description6,Price6
0,BIRDE,Combo Pack Of 2 Casual Shoes Sneakers For Men,₹499
1,RapidBox,Sneakers For Men,₹549
2,Labbin,Sneakers For Men,₹349
3,PUMA,Buzz Sneakers For Men,"₹1,149"
4,PUMA,Hustle V2 Sneakers For Men,"₹1,499"
...,...,...,...
95,aadi,RS-Z Reinvention Sneakers For Men,₹299
96,HOTSTYLE,HRXLB-2C Sneakers For Men,₹299
97,aadi,Original Luxury Branded Fashionable Men's Casu...,₹399
98,PUMA,Sneakers For Men,"₹4,421"
99,HRX by Hrithik Roshan,Hustle V2 Sneakers For Men,"₹1,047"

In [373]:
# Q7
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.amazon.in/")

In [374]:
Product7=driver.find_element(By.ID,"twotabsearchtextbox")
Product7.send_keys('Laptop')

In [376]:
search7=driver.find_element(By.ID,"nav-search-submit-button")
search7.click()
time.sleep(3)

In [377]:
i7=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[6]/span[8]/li/span/a/div")
i7.click()

In [378]:
Title7=[]
Rating7=[]
Price7=[]

In [379]:
Titles7_tags=driver.find_elements(By.XPATH,'//span[@class="a-size-medium a-color-base a-text-normal"]')
for i in Titles7_tags[0:10]:
    Titles7=i.text
    Title7.append(Titles7)
Ratings7_tags=driver.find_elements(By.XPATH,'//i[@class="a-icon a-icon-star-small a-star-small-4 aok-align-bottom"]')
for i in Ratings7_tags[0:10]:
    Ratings7=i.text
    Rating7.append(Ratings7)
Prices7_tags=driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
for i in Prices7_tags[0:10]:
    Prices7=i.text
    Price7.append(Prices7)

In [380]:
import pandas as pd
df7=pd.DataFrame({'Title': Title7[0:10],'Rating':Rating7[0:10],'Price': Price7[0:10]})
df7

                                               Title Rating   Price
0  Dell Vostro 3420 Laptop, Intel Core i5-1135G7,...         54,490
1  Lenovo IdeaPad Slim 3 Intel Core i5 12th Gen 1...         55,400
2  Dell Vostro 3510 Laptop, Intel Core i5-1135G7/...         52,490
3  (Renewed) DELL Latitude 5490 Core i5 7th Gen L...         79,490
4  HP Pavilion x360 13th Gen Intel Core i5-1335U ...         54,990
5  HP 15s, 12th Gen Intel Core i5 8GB RAM/512GB S...         49,490
6  Dell Vostro 3420 Laptop, Intel Core i5-1135G7,...         58,490
7  Dell Inspiron 3520 Laptop,12th Gen Intel Core ...         50,999
8  Xiaomi NotebookPro QHD+ IPS AntiGlare Display ...         66,800
9  HP Pavilion 14 12th Gen Intel Core i5 16GB RAM...         58,990

In [381]:
# Q8
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.azquotes.com/")
time.sleep(3)

In [382]:
topclick=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a")
topclick.click()
time.sleep(5)

In [383]:
Quote=[]
Author=[]
Type_of_Quotes=[]

In [384]:
start=0
end=20
for page in range(start,end):
    Quotes=driver.find_elements(By.XPATH,'//a[@class="title"]')
    for i in Quotes:
        Quote.append(i.text)
    Authors=driver.find_elements(By.XPATH,'//div[@class="author"]')
    for i in Authors:
        Author.append(i.text)
    Type_of_Quotes1=driver.find_elements(By.XPATH,'//div[@class="tags"]')
    for i in Type_of_Quotes1:
        Type_of_Quotes.append(i.text)
    
    Next=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[3]/li[3]/a")
    Next.click() 
    time.sleep(1)

In [385]:
import pandas as pd
df8=pd.DataFrame({'Quote': Quote[0:1000],'Author':Author[0:1000],'Type of Quotes': Type_of_Quotes[0:1000]})
df8

,Quote,Author,Type of Quotes
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,"When one door closes, another opens; but we of...",Alexander Graham Bell,"Love, Inspirational, Life"
996,"Don't find fault, find a remedy.",Henry Ford,"Inspirational, Motivational, Positive"
997,I used to think the worst thing in life was to...,Robin Williams,"Love, Life, Lonely"
998,Friends and good manners will carry you where ...,Margaret Walker,"Love, Inspirational, Friendship"
999,"If you want to make a permanent change, stop f...",T. Harv Eker,"Inspirational, Change, Inspiring"

In [386]:
# Q9
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.jagranjosh.com/")
time.sleep(3)

In [391]:
GK=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/div/div[1]/div/div[5]/div/div[1]/header/div[3]/ul/li[3]/a")
GK.click()
time.sleep(3)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[1]/div/div[1]/div/div[5]/div/div[1]/header/div[3]/ul/li[3]/a"}
  (Session info: chrome=114.0.5735.91)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00AFA813+48355]
	(No symbol) [0x00A8C4B1]
	(No symbol) [0x00995358]
	(No symbol) [0x009C09A5]
	(No symbol) [0x009C0B3B]
	(No symbol) [0x009EE232]
	(No symbol) [0x009DA784]
	(No symbol) [0x009EC922]
	(No symbol) [0x009DA536]
	(No symbol) [0x009B82DC]
	(No symbol) [0x009B93DD]
	GetHandleVerifier [0x00D5AABD+2539405]
	GetHandleVerifier [0x00D9A78F+2800735]
	GetHandleVerifier [0x00D9456C+2775612]
	GetHandleVerifier [0x00B851E0+616112]
	(No symbol) [0x00A95F8C]
	(No symbol) [0x00A92328]
	(No symbol) [0x00A9240B]
	(No symbol) [0x00A84FF7]
	BaseThreadInitThunk [0x765400C9+25]
	RtlGetAppContainerNamedObjectPath [0x77127B4E+286]
	RtlGetAppContainerNamedObjectPath [0x77127B1E+238]

In [392]:
list1=driver.find_element(By.XPATH,"/html/body/div[1]/div/div/div[2]/div/div[10]/div/div/ul/li[2]/a")
list1.click()
time.sleep(3)

ElementClickInterceptedException: Message: element click intercepted: Element <a href="https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1">...</a> is not clickable at point (753, 564). Other element would receive the click: <div style="" id="gdprbx">...</div>
  (Session info: chrome=114.0.5735.91)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00AFA813+48355]
	(No symbol) [0x00A8C4B1]
	(No symbol) [0x00995358]
	(No symbol) [0x009C5062]
	(No symbol) [0x009C3B98]
	(No symbol) [0x009C239B]
	(No symbol) [0x009C179E]
	(No symbol) [0x009B9F5C]
	(No symbol) [0x009DA73C]
	(No symbol) [0x009B9A36]
	(No symbol) [0x009DAA94]
	(No symbol) [0x009EC922]
	(No symbol) [0x009DA536]
	(No symbol) [0x009B82DC]
	(No symbol) [0x009B93DD]
	GetHandleVerifier [0x00D5AABD+2539405]
	GetHandleVerifier [0x00D9A78F+2800735]
	GetHandleVerifier [0x00D9456C+2775612]
	GetHandleVerifier [0x00B851E0+616112]
	(No symbol) [0x00A95F8C]
	(No symbol) [0x00A92328]
	(No symbol) [0x00A9240B]
	(No symbol) [0x00A84FF7]
	BaseThreadInitThunk [0x765400C9+25]
	RtlGetAppContainerNamedObjectPath [0x77127B4E+286]
	RtlGetAppContainerNamedObjectPath [0x77127B1E+238]

In [ ]:
Name=[]
Born_Dead=[]
Term_of_Office=[]
Remarks=[]

In [ ]:
names1_tags=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div/div[4]/span/div[3]/table/tbody/tr[2]/td[2]/p/strong/a')
    names1=i.text
    Name.append(names1)
Borndead_tags=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div/div[4]/span/div[2]/table/tbody/tr[2]/td[3]')
for i in Borndead_tags[0:100]:
    Borndead=i.text
    Born_Dead.append(Borndead)
Term_tags=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div/div[4]/span/div[2]/table/tbody/tr[2]/td[4]')
for i in Term_tags[0:100]:
    Term=i.text
    Term_of_Office.append(Term)
Remarks1_tags=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div/div[4]/span/div[2]/table/tbody/tr[2]/td[5]')
for i in Remarks1_tags[0:100]:
    Remarks1=i.text
    Remarks.append(Remarks1)

In [ ]:
import pandas as pd
df9=pd.DataFrame({'Prime Ministers name': Name[0:100],'Born-Dead':Born_Dead[0:100],'Term of Office': Term_of_Office[0:100],'Remarks':Remarks[0:100]})
df9

In [393]:
# Q10
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.motor1.com/")

In [394]:
expcars=driver.find_element(By.ID,"search_input")
expcars.send_keys('50 most expensive cars')

In [395]:
search10=driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/div/div[3]/div/div/div/form/button[1]")
search10.click()

In [398]:
search11=driver.find_element(By.XPATH,"/html/body/div[3]/div[9]/div/div[1]/div/div/div[2]/div/div[1]/h3/a")
search11.click()
time.sleep(5)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[9]/div/div[1]/div/div/div[2]/div/div[1]/h3/a"}
  (Session info: chrome=114.0.5735.91)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00AFA813+48355]
	(No symbol) [0x00A8C4B1]
	(No symbol) [0x00995358]
	(No symbol) [0x009C09A5]
	(No symbol) [0x009C0B3B]
	(No symbol) [0x009EE232]
	(No symbol) [0x009DA784]
	(No symbol) [0x009EC922]
	(No symbol) [0x009DA536]
	(No symbol) [0x009B82DC]
	(No symbol) [0x009B93DD]
	GetHandleVerifier [0x00D5AABD+2539405]
	GetHandleVerifier [0x00D9A78F+2800735]
	GetHandleVerifier [0x00D9456C+2775612]
	GetHandleVerifier [0x00B851E0+616112]
	(No symbol) [0x00A95F8C]
	(No symbol) [0x00A92328]
	(No symbol) [0x00A9240B]
	(No symbol) [0x00A84FF7]
	BaseThreadInitThunk [0x765400C9+25]
	RtlGetAppContainerNamedObjectPath [0x77127B4E+286]
	RtlGetAppContainerNamedObjectPath [0x77127B1E+238]

In [399]:
Car_Name=[]
Price=[]

In [400]:
carname_tags=driver.find_elements(By.XPATH,'//h3[@class="subheader"]')
for i in carname_tags[0:50]:
    carname=i.text
    Car_Name.append(carname)
carprice_tags=driver.find_elements(By.XPATH,'//i[@class="a-icon a-icon-star-small a-star-small-4 aok-align-bottom"]')
for i in carprice_tags[0:50]:
    carprice=i.text
    Price.append(carprice)

In [401]:
print(len(Car_Name),len(Price))

50 0

In [404]:
import pandas as pd
df10=pd.DataFrame({'Car Name': Car_Name[0:50]})
df10

                           Car Name
0                     De Tomaso P72
1                 Ferrari LaFerrari
2                     Pagani Huayra
3                      McLaren Elva
4                       Czinger 21C
5                     Ferrari Monza
6                Gordon Murray T.33
7                 Koenigsegg Gemera
8                       Zenvo TSR-S
9                Hennessey Venom F5
10                  Bentley Bacalar
11    Hispano Suiza Carmen Boulogne
12           Bentley Mulliner Batur
13                     Deus Vayanne
14                      SSC Tuatara
15                      Lotus Evija
16              Aston Martin Vulcan
17                       Delage D12
18                McLaren Speedtail
19                     Rimac Nevera
20                    Pagani Utopia
21             Pininfarina Battista
22                Ferrari FXX K Evo
23               Gordon Murray T.50
24             Lamborghini Countach
25         Mercedes-AMG Project One
26              Aston Martin Victor
27      Hennessey Venom F5 Roadster
28                 Koenigsegg Jesko
29            Aston Martin Valkyrie
30        W Motors Lykan Hypersport
31                    McLaren Solus
32        Pagani Huayra Roadster BC
33         Bugatti Chiron Pur Sport
34                 Lamborghini Sian
35                 Koenigsegg CC850
36  Bugatti Chiron Super Sport 300+
37               Lamborghini Veneno
38                   Bugatti Bolide
39                  Bugatti Mistral
40              Pagani Huayra Imola
41                     Bugatti Divo
42              SP Automotive Chaos
43                 Pagani Codalunga
44         Mercedes-Maybach Exelero
45               Bugatti Centodieci
46          Bugatti Chiron Profilée
47             Rolls-Royce Sweptail
48         Bugatti La Voiture Noire
49           Rolls-Royce Boat Tail*